dbquestion/Models/Administrator.cs
using System;
using System.Collections.Generic;

namespace dbquestion.Models;

public partial class Administrator
{
    public int Administratorid { get; set; }

    public string Username { get; set; } = null!;

    public string Passwordhash { get; set; } = null!;
}

dbquestion/Controllers/AdministratorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using dbquestion.Models;
using dbquestion.Data;
using Microsoft.AspNetCore.Authorization;

namespace dbquestion.Controllers
{
    [Authorize]
    public class AdministratorController : Controller
    {
        private readonly QuestionsContext _context;

        public AdministratorController(QuestionsContext context)
        {
            _context = context;
        }

        // GET: Administrator
        public async Task<IActionResult> Index()
        {
            var administrators = await _context.Administrators.ToListAsync();
            // Получение данных о прохождениях теста
            var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

            // Передача данных в представление
            ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
            ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;
            return View(administrators);
        }
  
        public async Task<IActionResult> AdminPanel()
        {
            // Получение данных о прохождениях теста
            var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

            // Передача данных в представление
            ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
            ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;
            return View();
        }

        // GET: Administrator/Create
        public IActionResult Create()
        {
            // Получение данных о прохождениях теста
            var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

            // Передача данных в представление
            ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
            ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;
            return View();
        }

        // POST: Administrator/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Administratorid,Username,Passwordhash")] Administrator administrator)
        {
            if (ModelState.IsValid)
            {
                _context.Add(administrator);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(administrator);
        }

        // GET: Administrator/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            // Получение данных о прохождениях теста
            var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

            // Передача данных в представление
            ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
            ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;
            if (id == null)
            {
                return NotFound();
            }

            Administrator administrator = await _context.Administrators.FindAsync(id);

            if (administrator == null)
            {
                return NotFound();
            }
            return View(administrator);
        }

        // POST: Administrator/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Administratorid,Username,Passwordhash")] Administrator administrator)
        {
            if (id != administrator.Administratorid || administrator == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(administrator);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdministratorExists(administrator.Administratorid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(administrator);
        }

        // GET: Administrator/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            // Получение данных о прохождениях теста
            var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

            // Передача данных в представление
            ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
            ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;
            if (id == null)
            {
                return NotFound();
            }

            Administrator administrator = await _context.Administrators
                .FirstOrDefaultAsync(m => m.Administratorid == id);

            if (administrator == null)
            {
                return NotFound();
            }

            return View(administrator);
        }

        // POST: Administrator/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Administrator administrator = await _context.Administrators.FindAsync(id);
            _context.Administrators.Remove(administrator);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdministratorExists(int id)
        {
            return _context.Administrators.Any(e => e.Administratorid == id);
        }
    }
}

dbquestion/Controllers/CriterionController.cs
using dbquestion.Data;
using dbquestion.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

public class CriterionController : Controller
{
    private readonly QuestionsContext _context;

    public CriterionController(QuestionsContext context)
    {
        _context = context;
    }

    // Действие для отображения списка критериев
    [Authorize(Policy = "RequireAdmin")]
    public IActionResult Index()
    {
        var criteria = _context.Criteria.Include(c => c.Options).ToList();
        // Получение данных о прохождениях теста
        var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

        // Передача данных в представление
        ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
        ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;
        return View(criteria);
    }

    // Действие для отображения формы добавления критерия
    [HttpGet]
    public IActionResult AddCriterion()
    {
        // Получение данных о прохождениях теста
        var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

        // Передача данных в представление
        ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
        ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;
        return View(new Criterion());
    }
    // Действие для обработки добавления критерия
    [HttpPost]
    public IActionResult AddCriterion(Criterion model, List<string> options, List<int?> scores)
    {
        if (ModelState.IsValid)
        {
            // Добавляем критерий
            _context.Criteria.Add(model);
            _context.SaveChanges();

            // Добавляем варианты ответов и связываем их с критерием
            for (int i = 0; i < options.Count; i++)
            {
                var option = new Option
                {
                    Optiontext = options[i],
                    Score = scores[i],
                    Criteriaid = model.Criteriaid  // Устанавливаем связь с критерием
                };

                model.Options.Add(option); // Добавляем вариант ответа в коллекцию критерия
                _context.Options.Add(option); // Добавляем вариант ответа в контекст данных
            }

            // Сохраняем изменения в базе данных
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        return View(model);
    }


    // Действие для отображения формы редактирования критерия
    [HttpGet]
    public IActionResult EditCriterion(int? id)
    {
        // Получение данных о прохождениях теста
        var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

        // Передача данных в представление
        ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
        ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;

        var model = new Criterion();

        if (id.HasValue)
        {
            model = _context.Criteria.Include(c => c.Options).FirstOrDefault(c => c.Criteriaid == id);

            if (model == null)
            {
                return NotFound();
            }
        }

        return View(model);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
 
    public async Task<IActionResult> EditCriterion(int id, Criterion model)
    {
        if (id != model.Criteriaid)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                var existingCriterion = await _context.Criteria
                    .Include(c => c.Options)
                    .FirstOrDefaultAsync(c => c.Criteriaid == id);

                if (existingCriterion != null)
                {
                    // Обновляем свойства критерия
                    existingCriterion.Criteriatext = model.Criteriatext;

                    // Удаляем существующие варианты ответов
                    _context.Options.RemoveRange(existingCriterion.Options);

                    // Добавляем новые варианты ответов из модели
                    foreach (var optionModel in model.Options)
                    {
                        var option = new Option
                        {
                            Optiontext = optionModel.Optiontext,
                            Score = optionModel.Score
                        };

                        existingCriterion.Options.Add(option);
                    }

                    await _context.SaveChangesAsync();
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                // Обработка исключения
            }
            return RedirectToAction(nameof(Index));
        }

        return View(model);
    }

    // Действие для отображения формы удаления критерия
    [HttpGet]
    public IActionResult DeleteCriterion(int id)
    {
        // Получение данных о прохождениях теста
        var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

        // Передача данных в представление
        ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
        ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;

        var criterion = _context.Criteria.Include(c => c.Options).FirstOrDefault(c => c.Criteriaid == id);

        if (criterion == null)
        {
            return NotFound();
        }

        return View(criterion);
    }

    // Действие для обработки удаления критерия
    [HttpPost, ActionName("DeleteCriterion")]
    public IActionResult ConfirmDeleteCriterion(int id)
    {
        var criterion = _context.Criteria.Include(c => c.Options).FirstOrDefault(c => c.Criteriaid == id);

        if (criterion == null)
        {
            return NotFound();
        }

        // Удаление связанных вариантов ответов
        _context.Options.RemoveRange(criterion.Options);

        // Удаление критерия
        _context.Criteria.Remove(criterion);
        _context.SaveChanges();

        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public IActionResult AddOptions(int id)
    {
        var criterion = _context.Criteria.Include(c => c.Options).FirstOrDefault(c => c.Criteriaid == id);

        if (criterion == null)
        {
            return NotFound();
        }

        var viewModel = new Option
        {
            Criteriaid = criterion.Criteriaid
        };

        return View(viewModel);
    }
    public IActionResult AddOptions(Option model)
    {
        if (ModelState.IsValid)
        {
            var criterion = _context.Criteria.Include(c => c.Options).FirstOrDefault(c => c.Criteriaid == model.Criteriaid);

            if (criterion != null)
            {
                foreach (var optionText in model.Optiontext)
                {
                    var option = new Option
                    {
                        Optiontext = model.Optiontext,
                        Score = model.Score,
                        Criteriaid = model.Criteriaid
                    };

                    criterion.Options.Add(option);
                }

                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
        }

        return View(model);
    }
}

dbquestion/Controllers/QuestionController.cs
using dbquestion.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using dbquestion.Models; // Замените на ваше пространство имен
using dbquestion.Data;
using Microsoft.AspNetCore.Authorization;

public class QuestionController : Controller
{
    private readonly QuestionsContext _context;

    public QuestionController(QuestionsContext context)
    {
        _context = context;
    }
    [Authorize(Policy = "RequireAdmin")]
    public IActionResult Index()
    {
        List<Question> questions = _context.Questions.ToList();
        // Получение данных о прохождениях теста
        var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

        // Передача данных в представление
        ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
        ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;
        return View(questions);
    }

    [HttpGet]
    public IActionResult Create()
    {
        // Получение данных о прохождениях теста
        var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

        // Передача данных в представление
        ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
        ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;

        return View();
    }

    [HttpPost]
    public IActionResult Create(Question question)
    {
        if (ModelState.IsValid)
        {
            _context.Questions.Add(question);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        

        return View(question);
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        // Получение данных о прохождениях теста
        var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

        // Передача данных в представление
        ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
        ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;

        var question = _context.Questions.Find(id);

        if (question == null)
        {
            return NotFound();
        }

        return View(question);
    }

    [HttpPost]
    public IActionResult Edit(Question question)
    {
        if (ModelState.IsValid)
        {
            _context.Entry(question).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        return View(question);
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        // Получение данных о прохождениях теста
        var testCompletion = _context.TestCompletions.FirstOrDefault(entry => entry.Date == DateTime.Now.Date);

        // Передача данных в представление
        ViewBag.DailyCount = testCompletion?.DailyCount ?? 0;
        ViewBag.TotalCount = testCompletion?.TotalCount ?? 0;

        var question = _context.Questions.Find(id);

        if (question == null)
        {
            return NotFound();
        }

        return View(question);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeleteConfirmed(int id)
    {
        var question = _context.Questions.Find(id);

        if (question != null)
        {
            _context.Questions.Remove(question);
            _context.SaveChanges();
        }

        return RedirectToAction(nameof(Index));
    }
}

dbquestion/Views/Administrator/AdminPanel.cshtml
<style>
    .card{
        background-color: #1dbcb9;
    }
</style>
<div class="admin-panel">
    <br>
    <h2>Панель администратора</h2>
    <br>
    <br>
   
    <div class="row">
        <div class="col-md-4">
            <div class="card admin-panel-item">
                <br>
                <br>
                <h3 class="text-center text-white">Вопросы</h3>
                <br>
                <br>
                <a class="button1 text-center" asp-controller="Question" asp-action="Index">Перейти</a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card admin-panel-item">
                <br>
                <br>
                <h3 class="text-center text-white">Критерии</h3>
                <br>
                <br>
                <a class="button1 text-center" asp-controller="Criterion" asp-action="Index">Перейти</a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card admin-panel-item">
                <br>
                <br>
                <h3 class="text-center text-white">Администраторы</h3>
                <br>
                <br>
                <a class="button1 text-center" asp-controller="Administrator" asp-action="Index">Перейти</a>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</div>

dbquestion/Views/Administrator/Create.cshtml
@model dbquestion.Models.Administrator

<body>
<h1>Создать новую</h1>

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
            <label asp-for="Username" class="control-label"><strong>Логин</strong></label>
            <textarea asp-for="Username" class="form-control" maxlength="50" placeholder="Введите логин..."></textarea>
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>

    <div class="form-group">
            <label asp-for="Passwordhash" class="control-label"><strong>Пароль</strong></label>
            <textarea asp-for="Passwordhash" class="form-control" maxlength="50" placeholder="Введите пароль..."><</textarea>
        <span asp-validation-for="Passwordhash" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Создать" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>
</body>

dbquestion/Views/Administrator/Delete.cshtml
@model dbquestion.Models.Administrator

<h1>Удаление</h1>

<h3>Вы уверены, что хотите удалить это?</h3>
<div>
    <h4>Администраторы</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Логин
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class="col-sm-2">
           Пароль
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Passwordhash)
        </dd>
    </dl>

    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Administratorid" />
        <input type="submit" value="Удалить" class="btn btn-danger" />
        <a asp-action="Index">Вернуться</a>
    </form>
</div>

dbquestion/Views/Administrator/Edit.cshtml
@model dbquestion.Models.Administrator

<h1>Редактировать</h1>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Administratorid" />

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Username" class="control-label"><strong>Логин</strong></label>
        <textarea asp-for="Username" class="form-control" maxlength="50" placeholder="Введите логин..."></textarea>
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Passwordhash" class="control-label"><strong>Пароль</strong></label>
        <textarea asp-for="Passwordhash" class="form-control" maxlength="50" placeholder="Введите пароль..."></textarea>
        <span asp-validation-for="Passwordhash" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

dbquestion/Views/Administrator/Index.cshtml
@model IEnumerable<dbquestion.Models.Administrator>

<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Администраторы</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
         <br>
        <h1>Администраторы</h1>
        <br>
        <p>
        <a class="btn btn-primary" asp-action="Create">Создать новую</a>
        </p>
    <table class="table table-striped">
            <thead>
                <tr>
                <th>id</th>
                <th>Логин</th>
                <th>Пароль</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Administratorid)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Passwordhash)
                        </td>
                    <td class="text-right">
                        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Administratorid">Редактировать</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Administratorid">Удалить</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
     <br>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>